# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coincache.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='coincache.proto',
  package='coypu.msg',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x63oincache.proto\x12\tcoypu.msg\"\xab\x01\n\tCoinCache\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05seqno\x18\x02 \x01(\x04\x12\x11\n\torigseqno\x18\x03 \x01(\x04\x12\x0f\n\x07seconds\x18\x04 \x01(\r\x12\x14\n\x0cmilliseconds\x18\x05 \x01(\r\x12\x0e\n\x06high24\x18\x06 \x01(\x01\x12\r\n\x05low24\x18\x07 \x01(\x01\x12\r\n\x05vol24\x18\x08 \x01(\x01\x12\x0c\n\x04open\x18\t \x01(\x01\x12\x0c\n\x04last\x18\n \x01(\x01\x62\x06proto3')
)




_COINCACHE = _descriptor.Descriptor(
  name='CoinCache',
  full_name='coypu.msg.CoinCache',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='coypu.msg.CoinCache.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqno', full_name='coypu.msg.CoinCache.seqno', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='origseqno', full_name='coypu.msg.CoinCache.origseqno', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seconds', full_name='coypu.msg.CoinCache.seconds', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='milliseconds', full_name='coypu.msg.CoinCache.milliseconds', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='high24', full_name='coypu.msg.CoinCache.high24', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='low24', full_name='coypu.msg.CoinCache.low24', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vol24', full_name='coypu.msg.CoinCache.vol24', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='open', full_name='coypu.msg.CoinCache.open', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last', full_name='coypu.msg.CoinCache.last', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=202,
)

DESCRIPTOR.message_types_by_name['CoinCache'] = _COINCACHE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CoinCache = _reflection.GeneratedProtocolMessageType('CoinCache', (_message.Message,), dict(
  DESCRIPTOR = _COINCACHE,
  __module__ = 'coincache_pb2'
  # @@protoc_insertion_point(class_scope:coypu.msg.CoinCache)
  ))
_sym_db.RegisterMessage(CoinCache)


# @@protoc_insertion_point(module_scope)
