apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
  - name: coypullvm
    image: gcr.io/massive-acrobat-227416/coypu_llvm:latest
    command:
    - cat
    tty: true
    image_pull_secrets:
      -name: docker-registry
