---
loggers: 
  ws-logger:
    level: debug
    file: websocket.log
  console:
    level: debug

interface: eth0

coypu:
  websocket:
    logger: console
    cpu: 1

do-kraken: false
do-gdax: true

gdax-symbols:
  - MANA-USDC
  - ETH-BTC
  - ETH-USD
  - LTC-BTC
  - LTC-USD
  - ETH-EUR
  - LTC-EUR
  - BCH-USD
  - BCH-BTC
  - BCH-EUR
  - BTC-USD
  - BTC-GBP
  - BTC-EUR
  - ETC-USD
  - ETC-EUR
  - ETC-BTC
  - ZRX-BTC
  - BTC-USDC
  - ETH-USDC
  - BAT-USDC
  - ZRX-EUR
  - ZRX-USD
  - CVC-USDC
  - DNT-USDC
  - LOOM-USDC

gdax-channels:
  - ticker
  - heartbeat
  - level2

do-server-test: false
