---
loggers: 
  ws-logger:
    level: debug
    file: websocket.log

interface: enp0s3
coypu-publish-path: stream/publish/data


coypu:
  websocket:
    logger: ws-logger
    cpu: 8

do-gdax: false

gdax-symbols: 
  - BTC-USD
  - BTC-EUR
  - ETH-USD
  - ETH-EUR
  - ETH-BTC
  - ZRX-USD
  - EOS-USD
  - BCH-USD

gdax-channels:
  - ticker
  - heartbeat
  - level2

do-server-test: false
