---
loggers: 
  ws-logger:
    level: debug
    file: websocket.log
  debug:
    level: debug
    file: debug.log

interface: enp0s3
coypu-publish-path: stream/publish/data


coypu:
  websocket:
    logger: ws-logger
    cpu: 8

do-kraken: true
kkraken-symbols:
  - XBT/EUR
  
kraken-symbols:
  - ADA/CAD
  - ADA/ETH
  - ADA/EUR
  - ADA/USD
  - ADA/XBT
  - BCH/EUR
  - BCH/USD
  - BCH/XBT
  - BSV/EUR
  - BSV/USD
  - BSV/XBT
  - DASH/EUR
  - DASH/USD
  - DASH/XBT
  - EOS/ETH
  - EOS/EUR
  - EOS/USD
  - EOS/XBT
  - GNO/ETH
  - GNO/EUR
  - GNO/USD
  - GNO/XBT
  - QTUM/CAD
  - QTUM/ETH
  - QTUM/EUR
  - QTUM/USD
  - QTUM/XBT
  - USDT/USD
  - ETC/ETH
  - ETC/XBT
  - ETC/EUR
  - ETC/USD
  - ETH/XBT
  - ETH/CAD
  - ETH/EUR
  - ETH/GBP
  - ETH/JPY
  - ETH/USD
  - LTC/XBT
  - LTC/EUR
  - LTC/USD
  - MLN/ETH
  - MLN/XBT
  - REP/ETH
  - REP/XBT
  - REP/EUR
  - REP/USD
  - STR/EUR
  - STR/USD
  - XBT/CAD
  - XBT/EUR
  - XBT/GBP
  - XBT/JPY
  - XBT/USD
  - BTC/CAD
  - BTC/EUR
  - BTC/GBP
  - BTC/JPY
  - BTC/USD
  - XDG/XBT
  - XLM/XBT
  - DOGE/XBT
  - STR/XBT
  - XLM/EUR
  - XLM/USD
  - XMR/XBT
  - XMR/EUR
  - XMR/USD
  - XRP/XBT
  - XRP/CAD
  - XRP/EUR
  - XRP/JPY
  - XRP/USD
  - ZEC/XBT
  - ZEC/EUR
  - ZEC/JPY
  - ZEC/USD
  - XTZ/CAD
  - XTZ/ETH
  - XTZ/EUR
  - XTZ/USD
  - XTZ/XBT
  
do-gdax: false
kraken-host: "ws-sandbox.kraken.com"
gdax-symbols:
  - MANA-USDC
  - ETH-BTC
  - ETH-USD
  - LTC-BTC
  - LTC-USD
  - ETH-EUR
  - LTC-EUR
  - BCH-USD
  - BCH-BTC
  - BCH-EUR
  - BTC-USD
  - BTC-GBP
  - BTC-EUR
  - ETC-USD
  - ETC-EUR
  - ETC-BTC
  - ZRX-BTC
  - BTC-USDC
  - ETH-USDC
  - BAT-USDC
  - ZRX-EUR
  - ZRX-USD
  - CVC-USDC
  - DNT-USDC
  - LOOM-USDC

  
gdax-channels:
  - ticker
  - heartbeat
  - level2

do-server-test: false
