---
loggers: 
  ws-logger:
    level: debug
    file: websocket.log

interface: enp0s3
coypu-publish-path: stream/publish/data


coypu:
  websocket:
    logger: ws-logger
    cpu: 8

do-gdax: true

gdax-symbols:
  - BTC-USD
  - BCH-USD
  - ETH-USD
  - ETC-USD
  - LTC-USD
  - ZRX-USD
  - BCH-BTC
  - ETH-BTC
  - ETC-BTC
  - LTC-BTC
  - ZRX-BTC
  - BTC-EUR
  - BCH-EUR
  - ETH-EUR
  - ETC-EUR
  - LTC-EUR
  - ZRX-EUR
  - BTC-GBP
  - BCH-GBP
  - ETH-GBP
  - ETC-GBP
  - LTC-GBP
  - BTC-USDC
  - ETH-USDC
  - BAT-USDC
  - ZEC-USDC
  - MANA-USDC
  - LOOM-USDC
  - DNT-USDC
  - CVC-USDC
  
gdax-channels:
  - ticker
  - heartbeat
  - level2

do-server-test: false
