---
loggers: 
  ws-logger:
    level: debug
    file: websocket.log

coypu: 
  websocket:
    logger: ws-logger
    cpu: 1

do-gdax: true

gdax-symbols: 
  - BTC-USD
  - ETH-USD
  - ETH-EUR
  - ETH-BTC
  - ZRX-USD
  - EOS-USD

gdax-channels:
  - ticker
  - heartbeat
  - level2

do-server-test: false
